name: Build and Upload Android APK
on:
  push:
    branches:
      - main
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: "projects/flutter-web-deploy-learning/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "github-action-940977073@flutter-web-deploy-learning.iam.gserviceaccount.com"
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - run: flutter --version
      #      - name: Build Android APK
      #        run: flutter build apk --release
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash
      - name: Upload APK to Firebase Storage
        run: |
          firebase storage:upload lib/main.dart \
            --project flutter-android-build-learning
      - name: Save metadata to Firestore
        run: |
          firebase firestore:push /builds \
            --data '{ "fileName": "app-release.apk", "uploadedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)" }' \
            --project flutter-android-build-learning
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
