name: Build and Upload Android APK
on:
  push:
    branches:
      - main
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: "projects/flutter-web-deploy-learning/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "github-action-940977073@flutter-web-deploy-learning.iam.gserviceaccount.com"
      - name: Upload file to Google Cloud Storage
        run: gcloud storage cp lib/main.dart gs://flutter-android-build-learning
      # - name: Clone repository
      #   uses: actions/checkout@v4
      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: stable
      #     flutter-version: 3.29.0
      # - run: flutter --version
      #      - name: Build Android APK
      #        run: flutter build apk --release
