name: Flutter CI
on:
  push:
    branches:
      - feature/**
jobs:
  flutter_ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - name: Generate firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS_DART }}' > firebase_options.dart
        working-directory: client/lib
      - name: Install dependencies
        run: flutter pub get
        working-directory: client
      - name: Run flutter analyze
        run: flutter analyze
        working-directory: client
