name: Flutter CI
on:
  push:
    branches:
      - feature/**
jobs:
  flutter_ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli
      - name: Add FlutterFire CLI to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect
      - name: Run flutterfire configure
        run: expect -c '
          spawn flutterfire configure
          expect "You have an existing `firebase.json` file and possibly already configured your project for Firebase. Would you prefer to reuse the values in your existing `firebase.json` file to configure your project? (y/n)" { send "y\r" }
          expect "Would you like to create a new Firebase project? (y/n)" { send "n\r" }
          expect eof '
        working-directory: client
      - run: flutter pub get
        working-directory: client
      - run: flutter analyze
        working-directory: client
